// 광양 제2 LNG터미널 증설공사 대시보드 데이터
// 보고기간: 2023년 1월 ~ 2026년 5월 (41개월, 1차계약 23.1~23.7 별도 관리)
// 갭 사유: DRM 보호 또는 보고서 미보유 (data_gap_reason 참조)
// 23.8월 이후 종합 진척률은 월간회의 엑셀 '2-1.공정현황' 시트의 '계' 행에서 EPC 누계 자동 추출

window.DASHBOARD_DATA = {
  "project": {
    "name": "광양 제2 LNG터미널 증설공사",
    "owner": "에너지건설 TF",
    "report_period": "2023년 1월 ~ 2026년 5월",
    "purpose": "에너지건설 TF 주요 지표 Dashboard 구축",
    "phases": [
      {
        "name": "1차 계약",
        "start": "2023-02",
        "end": "2023-07",
        "desc": "기초공사 (강관파일·지반개량)"
      },
      {
        "name": "본 계약",
        "start": "2023-08",
        "end": null,
        "desc": "#7,8탱크 본격 증설공사"
      }
    ],
    "data_gaps": [
      "2023-01",
      "2023-02",
      "2023-03",
      "2023-04",
      "2023-05",
      "2023-06",
      "2023-07",
      "2023-08",
      "2023-10"
    ],
    "data_gap_reason": {
      "2023-01": "1차계약(지반개량) 진행기간 — phase1_progress 참조",
      "2023-02": "1차계약(지반개량) — phase1_progress.tank78_actual 참조",
      "2023-03": "1차계약(지반개량) — phase1_progress.tank78_actual 참조",
      "2023-04": "1차계약(지반개량) — phase1_progress.tank78_actual 참조",
      "2023-05": "1차계약(지반개량) — phase1_progress.tank78_actual 참조",
      "2023-06": "1차계약(지반개량) — phase1_progress.tank78_actual 참조",
      "2023-07": "1차계약(지반개량) 종료 — phase1_progress.tank78_actual 참조",
      "2023-08": "1차→본계약 전환월 — 엑셀 1차계약 carryover 값(72.75%)이므로 종합 null 처리",
      "2023-10": "월간회의 엑셀 미존재 (23.10월_Final 파일 부재)"
    },
    "data_source_note": "23.9월~25.5월 종합 진척률은 월간회의 엑셀 '2-1.공정현황' 시트의 '계' 행에서 EPC 누계 자동 추출. 25.6월~26.5월은 기존 PPT 보고서 추출값 보존 + 2026-04는 엑셀 변환본에서 추출. 두 출처 사이에 가중치/scope 차이가 있어 25.5→25.6월 사이에 시각적 단차가 발생할 수 있음 (Excel 41.68% → PPT 63.26%)."
  },
  "progress": {
    "months": [
      "2023-01",
      "2023-02",
      "2023-03",
      "2023-04",
      "2023-05",
      "2023-06",
      "2023-07",
      "2023-08",
      "2023-09",
      "2023-10",
      "2023-11",
      "2023-12",
      "2024-01",
      "2024-02",
      "2024-03",
      "2024-04",
      "2024-05",
      "2024-06",
      "2024-07",
      "2024-08",
      "2024-09",
      "2024-10",
      "2024-11",
      "2024-12",
      "2025-01",
      "2025-02",
      "2025-03",
      "2025-04",
      "2025-05",
      "2025-06",
      "2025-07",
      "2025-08",
      "2025-09",
      "2025-10",
      "2025-11",
      "2025-12",
      "2026-01",
      "2026-02",
      "2026-03",
      "2026-04",
      "2026-05"
    ],
    "종합": {
      "plan": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        24.07,
        null,
        28.18,
        30.83,
        13.73,
        15.74,
        14.96,
        16.04,
        17.1,
        18.6,
        22.89,
        25.27,
        28.43,
        24.51,
        35.25,
        28.75,
        30.12,
        32.33,
        35.68,
        38.92,
        44.36,
        61.65,
        65.12,
        68.83,
        73.42,
        77.27,
        81.36,
        84.86,
        88.73,
        91.96,
        94.37,
        92.7,
        94.84
      ],
      "actual": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        21.23,
        null,
        27.84,
        30.37,
        13.72,
        15.92,
        16.6,
        18.07,
        19.3,
        20.0,
        22.26,
        25.37,
        29.61,
        22.64,
        36.29,
        25.82,
        28.15,
        29.99,
        33.34,
        38.35,
        41.68,
        63.26,
        66.98,
        69.31,
        72.3,
        73.81,
        77.79,
        80.55,
        82.2,
        86.16,
        88.99,
        84.03,
        87.12
      ]
    },
    "육상부": {
      "plan": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        56.16,
        59.76,
        63.43,
        68.41,
        73.13,
        77.82,
        81.84,
        86.7,
        90.73,
        93.71,
        null,
        null
      ],
      "actual": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        54.79,
        58.63,
        60.99,
        63.62,
        65.14,
        70.23,
        73.14,
        75.09,
        80.86,
        84.9,
        null,
        null
      ]
    },
    "해상부": {
      "plan": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        73.06,
        76.0,
        79.67,
        83.83,
        85.88,
        88.72,
        91.15,
        92.78,
        94.38,
        95.65,
        null,
        null
      ],
      "actual": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        80.86,
        84.06,
        86.24,
        90.35,
        91.83,
        93.5,
        95.97,
        96.7,
        96.96,
        97.3,
        null,
        null
      ]
    },
    "154kV": {
      "plan": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        81.16,
        91.83,
        95.42,
        98.6,
        96.67,
        98.7,
        99.9,
        100.0,
        100.0,
        null,
        null
      ],
      "actual": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        84.51,
        92.44,
        92.98,
        94.2,
        98.31,
        98.31,
        99.53,
        100.0,
        100.0,
        null,
        null
      ]
    }
  },
  "manpower": {
    "months": [
      "2023-01",
      "2023-02",
      "2023-03",
      "2023-04",
      "2023-05",
      "2023-06",
      "2023-07",
      "2023-08",
      "2023-09",
      "2023-10",
      "2023-11",
      "2023-12",
      "2024-01",
      "2024-02",
      "2024-03",
      "2024-04",
      "2024-05",
      "2024-06",
      "2024-07",
      "2024-08",
      "2024-09",
      "2024-10",
      "2024-11",
      "2024-12",
      "2025-01",
      "2025-02",
      "2025-03",
      "2025-04",
      "2025-05",
      "2025-06",
      "2025-07",
      "2025-08",
      "2025-09",
      "2025-10",
      "2025-11",
      "2025-12",
      "2026-01",
      "2026-02",
      "2026-03",
      "2026-04",
      "2026-05"
    ],
    "종합": {
      "manager": [
        null,
        16,
        16,
        16,
        17,
        17,
        17,
        18,
        18,
        20,
        22,
        null,
        38,
        null,
        36,
        38,
        37,
        35,
        50,
        50,
        46,
        null,
        51,
        null,
        null,
        null,
        null,
        null,
        null,
        61,
        68,
        70,
        73,
        69,
        68,
        67,
        71,
        65,
        63,
        null,
        null
      ],
      "partner": [
        null,
        95,
        62,
        58,
        116,
        101,
        99,
        125,
        125,
        161,
        148,
        null,
        164,
        null,
        240,
        249,
        216,
        221,
        294,
        387,
        416,
        null,
        450,
        null,
        null,
        null,
        null,
        null,
        null,
        640,
        735,
        675,
        661,
        713,
        669,
        651,
        595,
        574,
        595,
        null,
        null
      ]
    },
    "육상부": {
      "manager": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        43,
        46,
        51,
        51,
        50,
        48,
        49,
        55,
        51,
        51,
        null,
        null
      ],
      "partner": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        520,
        600,
        559,
        545,
        618,
        588,
        603,
        567,
        540,
        569,
        null,
        null
      ]
    },
    "해상부": {
      "manager": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        18,
        18,
        17,
        20,
        17,
        18,
        17,
        15,
        13,
        11,
        null,
        null
      ],
      "partner": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        120,
        120,
        106,
        106,
        90,
        70,
        42,
        23,
        30,
        22,
        null,
        null
      ]
    },
    "154kV": {
      "manager": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        2,
        2,
        2,
        2,
        2,
        1,
        1,
        1,
        0,
        null,
        null
      ],
      "partner": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        10,
        10,
        10,
        5,
        11,
        6,
        5,
        4,
        0,
        null,
        null
      ]
    }
  },
  "no_accident_days": {
    "months": [
      "2023-01",
      "2023-02",
      "2023-03",
      "2023-04",
      "2023-05",
      "2023-06",
      "2023-07",
      "2023-08",
      "2023-09",
      "2023-10",
      "2023-11",
      "2023-12",
      "2024-01",
      "2024-02",
      "2024-03",
      "2024-04",
      "2024-05",
      "2024-06",
      "2024-07",
      "2024-08",
      "2024-09",
      "2024-10",
      "2024-11",
      "2024-12",
      "2025-01",
      "2025-02",
      "2025-03",
      "2025-04",
      "2025-05",
      "2025-06",
      "2025-07",
      "2025-08",
      "2025-09",
      "2025-10",
      "2025-11",
      "2025-12",
      "2026-01",
      "2026-02",
      "2026-03",
      "2026-04",
      "2026-05"
    ],
    "육상부": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      80,
      111,
      142,
      172,
      203,
      233,
      264,
      295,
      323,
      354,
      null,
      null
    ],
    "해상부": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      648,
      679,
      710,
      740,
      771,
      801,
      832,
      863,
      891,
      922,
      null,
      null
    ],
    "154kV": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      242,
      273,
      303,
      334,
      364,
      395,
      426,
      454,
      null,
      null,
      null
    ]
  },
  "safety_audit_land": {
    "months": [
      "2023-01",
      "2023-02",
      "2023-03",
      "2023-04",
      "2023-05",
      "2023-06",
      "2023-07",
      "2023-08",
      "2023-09",
      "2023-10",
      "2023-11",
      "2023-12",
      "2024-01",
      "2024-02",
      "2024-03",
      "2024-04",
      "2024-05",
      "2024-06",
      "2024-07",
      "2024-08",
      "2024-09",
      "2024-10",
      "2024-11",
      "2024-12",
      "2025-01",
      "2025-02",
      "2025-03",
      "2025-04",
      "2025-05",
      "2025-06",
      "2025-07",
      "2025-08",
      "2025-09",
      "2025-10",
      "2025-11",
      "2025-12",
      "2026-01",
      "2026-02",
      "2026-03",
      "2026-04",
      "2026-05"
    ],
    "추락": [
      null,
      27,
      26,
      27,
      16,
      26,
      23,
      42,
      42,
      52,
      26,
      null,
      53,
      null,
      35,
      31,
      28,
      18,
      23,
      13,
      18,
      null,
      28,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      77,
      53,
      62,
      null,
      null
    ],
    "전도": [
      null,
      21,
      20,
      16,
      19,
      24,
      23,
      32,
      40,
      40,
      36,
      null,
      44,
      null,
      33,
      27,
      32,
      12,
      18,
      17,
      26,
      null,
      50,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      90,
      61,
      70,
      null,
      null
    ],
    "낙하/비래": [
      null,
      20,
      29,
      24,
      31,
      21,
      26,
      22,
      44,
      39,
      28,
      null,
      38,
      null,
      26,
      34,
      19,
      13,
      25,
      19,
      31,
      null,
      24,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      48,
      43,
      44,
      null,
      null
    ],
    "감전": [
      null,
      35,
      40,
      19,
      20,
      44,
      17,
      31,
      22,
      38,
      29,
      null,
      23,
      null,
      34,
      34,
      21,
      13,
      37,
      60,
      23,
      null,
      47,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      34,
      29,
      40,
      null,
      null
    ],
    "충돌/협착": [
      null,
      10,
      19,
      21,
      20,
      13,
      9,
      40,
      22,
      29,
      17,
      null,
      19,
      null,
      3,
      11,
      15,
      5,
      15,
      9,
      24,
      null,
      15,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      39,
      45,
      33,
      null,
      null
    ],
    "붕괴/도괴": [
      null,
      0,
      4,
      4,
      3,
      6,
      1,
      1,
      2,
      1,
      3,
      null,
      4,
      null,
      0,
      5,
      2,
      2,
      2,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      13,
      2,
      6,
      null,
      null
    ],
    "화재/폭발": [
      null,
      14,
      25,
      24,
      26,
      18,
      11,
      14,
      18,
      20,
      34,
      null,
      17,
      null,
      22,
      18,
      13,
      27,
      11,
      7,
      14,
      null,
      18,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      17,
      16,
      17,
      null,
      null
    ],
    "질식": [
      null,
      0,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      null,
      1,
      null,
      0,
      0,
      1,
      0,
      0,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      0,
      0,
      0,
      null,
      null
    ],
    "기타": [
      null,
      32,
      45,
      33,
      42,
      42,
      47,
      44,
      34,
      48,
      24,
      null,
      36,
      null,
      66,
      58,
      28,
      33,
      58,
      48,
      42,
      null,
      75,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      122,
      105,
      141,
      null,
      null
    ]
  },
  "safety_edu_land": {
    "months": [
      "2023-01",
      "2023-02",
      "2023-03",
      "2023-04",
      "2023-05",
      "2023-06",
      "2023-07",
      "2023-08",
      "2023-09",
      "2023-10",
      "2023-11",
      "2023-12",
      "2024-01",
      "2024-02",
      "2024-03",
      "2024-04",
      "2024-05",
      "2024-06",
      "2024-07",
      "2024-08",
      "2024-09",
      "2024-10",
      "2024-11",
      "2024-12",
      "2025-01",
      "2025-02",
      "2025-03",
      "2025-04",
      "2025-05",
      "2025-06",
      "2025-07",
      "2025-08",
      "2025-09",
      "2025-10",
      "2025-11",
      "2025-12",
      "2026-01",
      "2026-02",
      "2026-03",
      "2026-04",
      "2026-05"
    ],
    "채용/작업변경": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      2857,
      2981,
      3205,
      null,
      null
    ],
    "특별교육": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      8630,
      8765,
      9159,
      null,
      null
    ],
    "관리감독자": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      2278,
      2381,
      2457,
      null,
      null
    ],
    "정기교육": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      11351,
      12366,
      13371,
      null,
      null
    ]
  },
  "incident_summary": [
    {
      "sub": "육상부",
      "공상": 2,
      "일반재해": 2,
      "중대재해": 0,
      "일반NearMiss": 0,
      "중대NearMiss": 4
    },
    {
      "sub": "해상부",
      "공상": 1,
      "일반재해": 3,
      "중대재해": 0,
      "일반NearMiss": 4,
      "중대NearMiss": 1
    },
    {
      "sub": "154kV",
      "공상": 0,
      "일반재해": 0,
      "중대재해": 0,
      "일반NearMiss": 1,
      "중대NearMiss": 0
    }
  ],
  "phase1_progress": {
    "months": [
      "2023-02",
      "2023-03",
      "2023-04",
      "2023-05",
      "2023-06",
      "2023-07",
      "2023-08",
      "2023-09",
      "2023-10",
      "2023-11"
    ],
    "phase": [
      "1차계약",
      "1차계약",
      "1차계약",
      "1차계약",
      "1차계약",
      "1차계약",
      "본계약",
      "본계약",
      "본계약",
      "본계약"
    ],
    "tank78_actual": [
      57.5,
      69.24,
      76.65,
      84.37,
      90.61,
      90.9,
      23.0,
      27.7,
      30.44,
      33.09
    ],
    "tank78_plan_ratio": [
      106.7,
      103.02,
      100.89,
      101.29,
      103.82,
      99.46,
      -0.14,
      -0.9,
      -0.4,
      -0.99
    ]
  },
  "tank6_progress": {
    "months": [
      "2023-02",
      "2023-03",
      "2023-04",
      "2023-05",
      "2023-06",
      "2023-07",
      "2023-08",
      "2023-09",
      "2023-10",
      "2023-11",
      "2024-01",
      "2024-03",
      "2024-04",
      "2024-05",
      "2024-06"
    ],
    "진척률": [
      60.3,
      63.21,
      67.63,
      70.98,
      73.47,
      77.3,
      78.42,
      78.6,
      81.47,
      84.83,
      92.46,
      95.75,
      97.68,
      98.34,
      100.0
    ]
  },
  "milestones": [
    {
      "date": "2023-02-23",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "[1차계약] #7탱크 강관파일 항타 진행 (94% 완료)",
      "status": "진행"
    },
    {
      "date": "2023-03-03",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "[1차계약] #7탱크 강관파일 항타 完",
      "status": "완료"
    },
    {
      "date": "2023-06-16",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "[1차계약] #8탱크 강관파일 항타 完",
      "status": "완료"
    },
    {
      "date": "2023-07-31",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "[1차계약] 설비구간 지반개량공사 完",
      "status": "완료"
    },
    {
      "date": "2023-08-01",
      "sub": "전체",
      "공종": "기획",
      "title": "[본계약] #7,8탱크 본격 증설공사 착수",
      "status": "착수"
    },
    {
      "date": "2023-09-22",
      "sub": "해상-부두공",
      "공종": "부두공",
      "title": "해상부 공사 착수",
      "status": "착수"
    },
    {
      "date": "2024-01-29",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "#6탱크 Large Opening 콘크리트 타설 (1터미널 마감)",
      "status": "완료"
    },
    {
      "date": "2024-01-30",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#6탱크 수압시험 충수",
      "status": "완료"
    },
    {
      "date": "2024-06-24",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#6탱크 LP LNG Pump 기동 Test (1터미널 종료)",
      "status": "완료"
    },
    {
      "date": "2024-06-30",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#6탱크(1터미널) 공정률 100% 달성",
      "status": "완료"
    },
    {
      "date": "2024-07-24",
      "sub": "육상-안전",
      "공종": "안전",
      "title": "제2 LNG터미널 무재해 일수 카운트 시작 (~24.07.24)",
      "status": "착수"
    },
    {
      "date": "2024-09-13",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "#7탱크 Roof 1단 2차 Concrete 타설",
      "status": "완료"
    },
    {
      "date": "2024-09-26",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "Process P/R 기초 거푸집 조립",
      "status": "진행"
    },
    {
      "date": "2024-11-12",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "#7탱크 Roof 2단 3차 Concrete 타설",
      "status": "완료"
    },
    {
      "date": "2024-11-19",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "#8탱크 Ring Beam Concrete 타설",
      "status": "완료"
    },
    {
      "date": "2024-11-23",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "주전기실 독립기초 Concrete 타설",
      "status": "완료"
    },
    {
      "date": "2025-06-04",
      "sub": "육상-전기",
      "공종": "전기",
      "title": "주전기실 1층 Cable Tray 설치 착수",
      "status": "착수"
    },
    {
      "date": "2025-06-20",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "벙커링부두 Pedestal Con'c 타설 完",
      "status": "완료"
    },
    {
      "date": "2025-06-25",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#8탱크 Inner Shell Plate 4단 설치 착수",
      "status": "착수"
    },
    {
      "date": "2025-06-28",
      "sub": "육상-건축",
      "공종": "건축",
      "title": "주전기실 2층 습식(블록) 공사 完",
      "status": "완료"
    },
    {
      "date": "2025-06-30",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#7탱크 Inner Shell Plate 6단 설치 착수",
      "status": "착수"
    },
    {
      "date": "2025-06-30",
      "sub": "육상-건축",
      "공종": "건축",
      "title": "본부빌딩 B 1층 습식(블록) 공사 完",
      "status": "완료"
    },
    {
      "date": "2025-07-01",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "#7, 8탱크 Elec. Duct Bank 착수",
      "status": "착수"
    },
    {
      "date": "2025-07-02",
      "sub": "육상-건축",
      "공종": "건축",
      "title": "BOG Comp. Shelter 철골 지조립 및 설치 착수",
      "status": "착수"
    },
    {
      "date": "2025-07-14",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "1터미널 SCV Wall Con'c 타설 完",
      "status": "완료"
    },
    {
      "date": "2025-07-15",
      "sub": "육상-건축",
      "공종": "건축",
      "title": "SOG Comp. Shelter 철골 지조립 및 설치 착수",
      "status": "착수"
    },
    {
      "date": "2025-07-22",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#7탱크 Inner Shell Plate 7단 설치 착수",
      "status": "착수"
    },
    {
      "date": "2025-07-25",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#8탱크 Inner Shell Plate 5단 설치 착수",
      "status": "착수"
    },
    {
      "date": "2025-07-31",
      "sub": "육상-전기",
      "공종": "전기",
      "title": "주전기실 2층 전기 Panel 설치 착수",
      "status": "착수"
    },
    {
      "date": "2025-08-28",
      "sub": "전기/154kV",
      "공종": "전기",
      "title": "LNG 전기실 TR측 154KV 케이블 접속 진행 完",
      "status": "완료"
    },
    {
      "date": "2025-08-30",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "1터미널 중화조 가시설 설치 完",
      "status": "완료"
    },
    {
      "date": "2025-08-30",
      "sub": "육상-건축",
      "공종": "건축",
      "title": "BOG 및 SOG Comp. Shelter 철골 설치 完",
      "status": "완료"
    },
    {
      "date": "2025-09-19",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "LNG 부두 Working Platform 상부 Pedestal Con'c 타설 完",
      "status": "완료"
    },
    {
      "date": "2025-09-19",
      "sub": "육상-전기",
      "공종": "전기",
      "title": "주전기실 1층 수전용 Cable 포설 完",
      "status": "완료"
    },
    {
      "date": "2025-09-28",
      "sub": "전기/154kV",
      "공종": "전기",
      "title": "154KV 케이블 AC 내전압 테스트 完",
      "status": "완료"
    },
    {
      "date": "2025-09-30",
      "sub": "육상-건축",
      "공종": "건축",
      "title": "주전기실 마감공사 90% 진행 및 Shelter류 철골설치 完",
      "status": "완료"
    },
    {
      "date": "2025-10-15",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#7탱크 Inner Shell Plate 9단 설치 착수",
      "status": "착수"
    },
    {
      "date": "2025-10-16",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "주전기실 소방 지중배관 터파기 착수",
      "status": "착수"
    },
    {
      "date": "2025-10-22",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "해상 JP(Joint Pier)-2 Pedestal 공사 착수",
      "status": "착수"
    },
    {
      "date": "2025-10-22",
      "sub": "육상-건축",
      "공종": "건축",
      "title": "주전기실 내외부 도장 完",
      "status": "완료"
    },
    {
      "date": "2025-10-27",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#8탱크 Inner Shell Plate 7단 설치 착수",
      "status": "착수"
    },
    {
      "date": "2025-10-27",
      "sub": "육상-전기",
      "공종": "전기",
      "title": "주전기실↔본부빌딩B 6.6kv Cable 포설 착수",
      "status": "착수"
    },
    {
      "date": "2025-10-30",
      "sub": "육상-건축",
      "공종": "건축",
      "title": "SOG Comp. Shelter 외부판넬 설치 完",
      "status": "완료"
    },
    {
      "date": "2025-10-31",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "오버헤드크레인 설치 및 완성검사 完",
      "status": "완료"
    },
    {
      "date": "2025-11-07",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "#8탱크 소방 지중배관 터파기 착수",
      "status": "착수"
    },
    {
      "date": "2025-11-07",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#7탱크 Inner Shell Plate 10단 설치 착수",
      "status": "착수"
    },
    {
      "date": "2025-11-12",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "BOG Comp. 설치 착수",
      "status": "착수"
    },
    {
      "date": "2025-11-14",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "해상 JP(Joint Pier)-2 Pedestal 설치 完",
      "status": "완료"
    },
    {
      "date": "2025-11-14",
      "sub": "육상-전기",
      "공종": "전기",
      "title": "본부빌딩 B 전기실 사용전 검사 完",
      "status": "완료"
    },
    {
      "date": "2025-11-14",
      "sub": "육상-건축",
      "공종": "건축",
      "title": "본부빌딩 B 옥상 누름 타설 完",
      "status": "완료"
    },
    {
      "date": "2025-11-19",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#8탱크 Inner Shell Plate 8단 설치 착수",
      "status": "착수"
    },
    {
      "date": "2025-11-28",
      "sub": "해상-부두공",
      "공종": "부두공",
      "title": "상부공 진행 - LNG부두 Fender 설치 中",
      "status": "완료"
    },
    {
      "date": "2025-11-29",
      "sub": "육상-건축",
      "공종": "건축",
      "title": "주전기실 이중바닥재 및 금속공사 完",
      "status": "완료"
    },
    {
      "date": "2025-12-01",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "주전기실 소방 지중배관 터파기 착수",
      "status": "착수"
    },
    {
      "date": "2025-12-01",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "#7탱크 Small Opening Closing 착수",
      "status": "착수"
    },
    {
      "date": "2025-12-18",
      "sub": "육상-건축",
      "공종": "건축",
      "title": "Gate House 철근 콘크리트 공사 完",
      "status": "완료"
    },
    {
      "date": "2025-12-24",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "BOG/SOG 압축기 설치 完",
      "status": "완료"
    },
    {
      "date": "2025-12-26",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#8탱크 Inner Shell Plate 9단 설치 착수",
      "status": "착수"
    },
    {
      "date": "2025-12-28",
      "sub": "해상-부두공",
      "공종": "부두공",
      "title": "상부공 진행 - LNG부두 Fender 및 Catwalk 설치 完",
      "status": "완료"
    },
    {
      "date": "2025-12-28",
      "sub": "전기/154kV",
      "공종": "전기",
      "title": "케이블 포설 및 결선 - 비상발전기~전기실 구간 완료",
      "status": "완료"
    },
    {
      "date": "2025-12-30",
      "sub": "육상-전기",
      "공종": "전기",
      "title": "본부빌딩 B 전기실 6.6kV 수전 完",
      "status": "완료"
    },
    {
      "date": "2025-12-31",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#7탱크 Anchor Strap Upper Part 설치 착수",
      "status": "착수"
    },
    {
      "date": "2025-12-31",
      "sub": "육상-건축",
      "공종": "건축",
      "title": "본부빌딩 B 내부 도장 및 마감공사 完",
      "status": "완료"
    },
    {
      "date": "2026-01-10",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#7탱크 Large Opening Closing 착수",
      "status": "착수"
    },
    {
      "date": "2026-01-10",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "탱크 Jib Crane 설치 完",
      "status": "완료"
    },
    {
      "date": "2026-01-13",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "#7탱크 Small Opening PT-Step4 完",
      "status": "완료"
    },
    {
      "date": "2026-01-15",
      "sub": "육상-전기",
      "공종": "전기",
      "title": "#7탱크 Cable 포설 착수",
      "status": "착수"
    },
    {
      "date": "2026-01-22",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#8탱크 Inner Shell Plate 10단 설치 착수",
      "status": "착수"
    },
    {
      "date": "2026-01-29",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "#8탱크 Small Opening PT-Step4 完",
      "status": "완료"
    },
    {
      "date": "2026-02-05",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#7탱크 Large Opening Closing 完",
      "status": "완료"
    },
    {
      "date": "2026-02-10",
      "sub": "전기/154kV",
      "공종": "전기",
      "title": "154kV 수전 完 (주전기실 154kV 수전)",
      "status": "완료"
    },
    {
      "date": "2026-02-11",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "#7탱크 Large Opening 콘크리트 타설 完",
      "status": "완료"
    },
    {
      "date": "2026-02-12",
      "sub": "해상-부두공",
      "공종": "부두공",
      "title": "LNG부두 오일펜스 설치 完",
      "status": "완료"
    },
    {
      "date": "2026-02-13",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#7탱크 수압시험 착수",
      "status": "착수"
    },
    {
      "date": "2026-02-20",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#8탱크 Inner Shell Plate 10단 용접 完",
      "status": "완료"
    },
    {
      "date": "2026-02-28",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "하역암 조립 및 설치 完",
      "status": "완료"
    },
    {
      "date": "2026-02-28",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "Ground Flare 설치 完",
      "status": "완료"
    },
    {
      "date": "2026-03-04",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#7탱크 수압시험 完",
      "status": "완료"
    },
    {
      "date": "2026-03-04",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#7,8탱크 Jib Crane 완성검사 完",
      "status": "완료"
    },
    {
      "date": "2026-03-05",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "#7탱크 Roof 도장 착수",
      "status": "착수"
    },
    {
      "date": "2026-03-11",
      "sub": "육상-토목",
      "공종": "토목",
      "title": "#7탱크 강선 인장 작업 完",
      "status": "완료"
    },
    {
      "date": "2026-03-14",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#7탱크 배수 및 내압시험 完",
      "status": "완료"
    },
    {
      "date": "2026-03-18",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "#8탱크 Large Opening Closing 착수",
      "status": "착수"
    },
    {
      "date": "2026-03-25",
      "sub": "육상-기계",
      "공종": "기계",
      "title": "질소·공기 배관 내압시험 完",
      "status": "완료"
    },
    {
      "date": "2026-03-31",
      "sub": "육상-건축",
      "공종": "건축",
      "title": "Gate House 마감공사 完",
      "status": "완료"
    }
  ],
  "next_month_plan": [
    {
      "date": "2026-04-06",
      "공종": "토목",
      "title": "#7탱크 벽체 도장 착수"
    },
    {
      "date": "2026-04-10",
      "공종": "전기",
      "title": "주전기실 정전 및 마무리 작업 完"
    },
    {
      "date": "2026-04-13",
      "공종": "기계",
      "title": "#7탱크 LP Pump 설치 착수"
    },
    {
      "date": "2026-04-17",
      "공종": "토목",
      "title": "#8탱크 Large Opening 타설 完"
    },
    {
      "date": "2026-04-20",
      "공종": "기계",
      "title": "#8탱크 수압시험 충수 착수"
    },
    {
      "date": "2026-04-21",
      "공종": "기계",
      "title": "#7탱크 벽체 보온 설치 完"
    },
    {
      "date": "2026-04-30",
      "공종": "기계",
      "title": "1·2터미널 연결배관 작업 完"
    },
    {
      "date": "2026-04-30",
      "공종": "건축",
      "title": "해상 전기실 천정 설치 完"
    }
  ]
};
